### ISSUE TITLE
Контент для рп

### ISSUE THREAD

**Issue by vlasooff** [VitaxaRusModding/Community#108]
- [x]  Паспорт State ID
- [x]  Показать паспорт
- [x]  Без сознания (Вызвать скорую) 
- [x]  Иконка продажи дома 
- [x]  Иконка входа 
- [ ]  Телефон 
- [x]  Эффект открытия машины на расстояние, закрытия

**Comment by ivanuhjv1974** [comment]
- [ ] тест

**Comment by ivanuhjv1974** [comment]
- [ ] Нпс которые будут принимать на работу, (механик, полицейский, банда, мафия) сделать тесты как на собеседования пример- нпс, которые не пускают на сталкер пока не пройдёшь опрос.

- [ ] Нпс будут выдавать тебе кит, например полицейский - рядовой, младший сержант, старший сержант и т.д..

**Comment by ivanuhjv1974** [comment]
- [x] Убрать место в руках у игрока.

- [ ] Убрать нижние панель с ником игрока

- [ ] При смерти одежда игрока с него не выпадает 

- [ ] Скрыть в чате, кто пишет бандит или гражданский просто будет написано неизвестный, а у фракций видно, что пишут именно они. Но чтобы в логах отображалось, кто пишет, чтобы можно было нон рпшников ловить.
