### ISSUE TITLE
RP: Создание нпц

### ISSUE THREAD

**Issue by vlasooff** [VitaxaRusModding/Community#124]
- [ ]  Нпц гражданские

Позже более подробней распишу список

**Comment by ivanuhjv1974** [comment]
- [ ] Ферма - минимум 2 квеста, максимум до 12, квест на выращивание. 0%

- [ ]  Начальный город- квесты.  0%

- [ ] Шахта добавить id руд и ювелира. 0%

- [ ] Рыбак квесты на улов рыбы. 0%

- [ ] Нпс путешественников с история и легендами. 0%

- [ ] Больница- нет мыслей... 0%

- [ ] Полицейский участок - нет мыслей.. 0%

- [ ] Аэропорт- нет мыслей. 0%

- [ ] Главный город - банк, забегаловки, отель и работа таксистом...реализовать. 0%

- [ ] Получение документов - реализовать. 0%

- [ ] Тюрьма- нет мыслей. 0%

- [x] Работа дайверов. 100%

- [ ] Работа машинистом - не вижу смысла в ней - переосмыслить ибо поезд на карте будет.

- [ ] Группировка Мафия.-реализация... 0% 

- [ ] Радиостанция - нету мыслей. 0% 

- [ ] Группировка Полиции- реализация 0%

- [ ] Лесопилка- локация готова на 75%/100%

- [ ] Ферма- локация готова на 50% / 100%

- [ ] Шахта - локация готова на 75% /100% 

- [ ] Тюрьма - локация готова на 0% /100% 

- [ ] Дома мафии - локация готова на 0% /100% 

- [ ] Аэропорт - локация готова на 0% /100% 

- [ ] Начальный город- локация готова на 45% /100% 

- [ ] Заправочная 75% /100% 

- [ ] Авианосец- локация готова на 0% /100% 

- [ ] Главный город локация готова на 25% /100% 

- [ ] Дополнительные квесты на ферме, после выполнение основных задач.  

- [ ] Затонувший авианосец с плюшками, и продумать другие локации. 

- [x] Пираты и поиск сокровища Флинта.  

- [ ] Госпиталь если у игрока мало хп, тебе дадут аптечку. - окажет медицинскую помощь

**Comment by vlasooff** [comment]
@ivanuhjv1974  Ты сделал чтобы фермер скупал ягоды?

**Comment by ivanuhjv1974** [comment]
> @ivanuhjv1974 Ты сделал чтобы фермер скупал ягоды?

торговец, что покупает есть и некоторые повара тоже покупают.
