### ISSUE TITLE
1-й Сервер

### ISSUE THREAD

**Issue by vlasooff** [VitaxaRusModding/Community#84]
- [x] Починить ПКП 

- [ ] Добавить Менеджер убийств 

- [x] Исправить баг, что если открыть /s и тебя убьют и выпадут все вещи от туда
Пока что всё что я вспомнил по первому

**Comment by ivanuhjv1974** [comment]
- [x] обновить сервер в зимний вариан

**Comment by vlasooff** [comment]
@ivanuhjv1974  Это будет отдельной задачей

**Comment by VitaxaRusModding** [comment]
> * [ обновить сервер в зимний вариант]

**Comment by vlasooff** [comment]
- [x] Выдать 76561198299138265 кит хеллуин
