### ISSUE TITLE
4-тый WW3

### ISSUE THREAD

**Issue by vlasooff** [VitaxaRusModding/Community#87]
- [ ]  Спавн машин замкнутыми для каждых команд.

- [ ]  Нельзя заходить на чужую базу

- [ ]  Новая карта

- [ ]  Прокачка

- [x]  Добавить ПКП

**Comment by ivanuhjv1974** [comment]
- [сразу зимний вариант с бурей и сиянием]

**Comment by ivanuhjv1974** [comment]
> * [ ]   Спавн машин замкнутыми для каждых команд.
> * [ ]   Нельзя заходить на чужую базу
> * [ ]   Новая карта
> * [ ]   Прокачка
> * [ ]   Добавить ПКП

///

**Comment by vlasooff** [comment]
- [ ]  Изменить вид от третьего лица

- [ ]  Сделать у технике бесконечные патроны

**Comment by ivanuhjv1974** [comment]
- [ ] часто 1 упоменнание  в чате спамиться по '100 раз'
