### ISSUE TITLE
Новогодние обновление

### ISSUE THREAD

**Issue by vlasooff** [VitaxaRusModding/Community#92]
- [ ]  Зимние карты

- [x]   Снег на сайте

- [ ]  Киты

- [ ]  НПЦ на карте

**Comment by ivanuhjv1974** [comment]
- [ ] Новогодний kit start 

- [ ] Новогодний kit com

**Comment by vlasooff** [comment]
- [ ] kit 2019
- [ ] kit snow
- [ ] kit Santa

**Comment by vlasooff** [comment]
- [ ] 1 кит по шт один бесплатно один платный навсегда

**Comment by ivanuhjv1974** [comment]
- [ ] зимний гилик или в магазин добавляй или кит старт или com сам выберай

**Comment by vlasooff** [comment]
@ivanuhjv1974 kit snow я уже написал
