### ISSUE TITLE
Мод пак

### ISSUE THREAD

**Issue by vlasooff** [VitaxaRusModding/Community#93]
- [ ]  Добавить дверь

- [ ]  Заменить оружие 

- [ ]  Новогодний контент

- [ ]  Исправить технику на 4-том

- [ ]  Обновить интерфейс 

- [x]  Удалить 80-тку

**Comment by ivanuhjv1974** [comment]
- [x] полностью удалить дигл

**Comment by ivanuhjv1974** [comment]
- [ ] добавить функцию гниение дома как в расте 3 дня чела нету начнёт гнить
