### ISSUE TITLE
Глобальные системы.

### ISSUE THREAD

**Issue by vlasooff** [VitaxaRusModding/Community#94]
- [x]  ПКП Основной

- [ ]  Образец клановой системы

- [x]  Система командных боём

- [ ]  Панель управления

**Comment by vlasooff** [comment]
**Система ПКП**

- [x] Основной интерфейс.

- [x] Статистика игрока.

- [ ] Статистика клана.

- [ ] Система вознаграждений.

- [x] Система часов.

**Comment by vlasooff** [comment]
**Панель управления** 

- [x]  Подключение к серверу


- [ ] Авторизация

- [ ] Подгрузка статистики сервера

**Comment by ivanuhjv1974** [comment]
- [x] Сделать, что кпк открывается на / и при повторном нажатии закрывается!

**Comment by VitaxaRusModding** [comment]
- [ ] УВЕРЕН

**Comment by ivanuhjv1974** [comment]
- [ ] когда пишешь /kits в открывается справа меню с доступными тебе китами /kit start, kit com, vote и т.д.

- [ ] можно так же запилить туда радио с музыкой от 2-го

**Comment by ivanuhjv1974** [comment]
- [ ] забыли про команду /bonus пересмотреть её использование и упоминание
