### ISSUE TITLE
Другое

### ISSUE THREAD

**Issue by vlasooff** [VitaxaRusModding/Community#95]
- [ ]  Добавить WW2

- [ ]  Добавить StarWars

- [ ]  RP Server

**Comment by ivanuhjv1974** [comment]
- [ ] Удалить дигл, он остался на 7 и 11 ( в рангах)

**Comment by ivanuhjv1974** [comment]
- [ ] Водная аренка, под тип 7-го и 11-го можно довести до ума, будет популярна, или наоборот заменить на 7 и новую карту поставить, без потерь рангов у людей

**Comment by ivanuhjv1974** [comment]
- [x] загрузить иконку проекта

**Comment by ivanuhjv1974** [comment]
- [ ] сделать отдельное окно, когда пишешь kits

**Comment by ivanuhjv1974** [comment]
- [ ] обновить иконку на сервах

**Comment by ivanuhjv1974** [comment]
- [ ] оповещение на других серварах, исправить, что 1xp-2 centa

**Comment by ivanuhjv1974** [comment]
- [ ] найти музыку на 2 серве  в сз и опубликовать в группе данную музыку

**Comment by ivanuhjv1974** [comment]
- [ ] Починить ивент Мега Зомби

**Comment by ivanuhjv1974** [comment]
- [ ] придумать новые ивенты

**Comment by ivanuhjv1974** [comment]
- [ ] добавить и на остальные сервера, что больше 5-ти в тиму не пустит

**Comment by ivanuhjv1974** [comment]
- [ ] спавн модовой техники

**Comment by ivanuhjv1974** [comment]
- [ ] исправить варн с /skype на /discord

**Comment by ivanuhjv1974** [comment]
- [ ] снять модерки где есть там снять 
1. 76561198350746549 
2. 76561198371492007 
3. 76561198137086385

**Comment by ivanuhjv1974** [comment]
- [ ] если у игрока нету 30 часов, его не пустит на сервер
